version: '2.1'
services:
  mysql:
    image: "mysql:5.7.23"
    hostname: mysql
    ports:
      - "3606:3606"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  petclinic:
    image: "spring/petclinic:18.09"
    hostname: petclinic
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy

