version: '2.1'
services:
  mysql:
    image: "mysql:5.7.23"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  petclinic1:
    image: "spring/petclinic:18.09"
    hostname: petclinic1
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sSL", "localhost:8080"]
      timeout: 20s
      retries: 10
  petclinic2:
    image: "spring/petclinic:18.09"
    hostname: petclinic2
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sSL", "localhost:8080"]
      timeout: 20s
      retries: 10
  nginx:
    image: "spring/petclinic:18.09-nginx"
    hostname: nginx
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - "petclinic1"
      - "petclinic2"
